[language-server]
csharp-ls = { command = "csharp-ls" }

[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs", "csx", "cake"]
roots = ["sln", "csproj"]
comment-token = "//"
indent = { tab-width = 4, unit = " " }
language-servers = [ "csharp-ls" ]

[[language]]
name = "python"
auto-format = true
